version: "3"

services:
  danmuji:
    image: danmuji:tmp4test
    build:
      context: ../..
      dockerfile: deploy/docker/Dockerfile
    env_file: .env
    ports:
      - "23333:23333"
    networks:
      - danmuji-network
    volumes:
      - "profileStore:/opt/store" # 持久化配置

networks:
  danmuji-network:
    driver: bridge

volumes:
  profileStore: